### ISSUE TITLE
Antibody integration

### ISSUE THREAD

**Issue by jostyee** [BrandonRoehl/zsh-clean#2]
This theme was compatible with [antibody](https://github.com/getantibody/antibody) , but recently updates broke it. `antibody bundle BrandonRoehl/zsh-clean` gets an error:

```
Usage: prompt <options>
Options:
    -c              Show currently selected theme and parameters
    -l              List currently available prompt themes
    -p [<themes>]   Preview given themes (defaults to all)
    -h [<theme>]    Display help (for given theme)
    -s <theme>      Set and save theme
    <theme>         Switch to new theme immediately (changes not saved)

Use prompt -h <theme> for help on specific themes.
```

**Comment by BrandonRoehl** [comment]
Can you run `echo $^fpath/prompt_clean_setup(N)` and tell me what the output is? It should be something like `.../zsh-clean/prompt_clean_setup` and `type prompt_clean_setup` should print off 
`prompt_clean_setup is a shell function from [same path as above]`

**Comment by jostyee** [comment]
```
$ echo $^fpath/prompt_clean_setup(N)

```

Should I set it manually?

**Comment by BrandonRoehl** [comment]
Neither of those will set anything they will just give me more information about your shell environment.
I'd like to get it working with all plugin managers that we can so id like to try and fix this.
If you want a manual fix right now you should check out https://github.com/BrandonRoehl/zsh-clean#zsh-stock this issue had to deal with moving to zsh built in prompt engine and away from standalone source files. However you can still source `prompt_clean_setup` manually.

**Comment by jostyee** [comment]
```bash
$ type prompt_clean_setup
prompt_clean_setup not found
```

**Comment by BrandonRoehl** [comment]
Looks like antibody is not adding the plugin repo to the `fpath` so I'll try and get a fix for it when I get back from work. Thanks for your patience and help

**Comment by BrandonRoehl** [comment]
I pushed a test to the plugin file that should add it to the `fpath` if it doesn't already exist. If you update it in your plugin manager it should work. I haven't had time to get Antibody up yet and will have to do more extensive testing later.
> [master@753d846](https://github.com/BrandonRoehl/zsh-clean/commit/753d846336c7abc4a6941b5fd265286a65690ad7)

**Comment by jostyee** [comment]
After update I got:

```
/Users/yee/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-BrandonRoehl-SLASH-zsh-clean/clean.plugin.zsh:11: command not found: promptinit
```

then I added `autoload -U promptinit; promptinit` above antibody load command, got another error:

```
Usage: prompt <options>
Options:
    -c              Show currently selected theme and parameters
    -l              List currently available prompt themes
    -p [<themes>]   Preview given themes (defaults to all)
    -h [<theme>]    Display help (for given theme)
    -s <theme>      Set and save theme
    <theme>         Switch to new theme immediately (changes not saved)

Use prompt -h <theme> for help on specific themes.
```

**Comment by BrandonRoehl** [comment]
Just fixed a method scoping issue because it looks like it runs the file from a different directory
